version: '3'
services:
  postgres:
    image: postgres:13.3
    container_name: "sso-demo_postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password123!
      - POSTGRES_DB=sso_demo_db
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - /var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: "sso-demo_pgadmin"
    ports:
      - "5000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@sample.com
      - PGADMIN_DEFAULT_PASSWORD=Password123!
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
